# Generated by Django 4.2.7 on 2025-05-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donateapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationplatform',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donationplatform',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationplatform',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donationplatform',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationplatform',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='donationplatform',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
